package user

import "fmt"

var adjectives = []string{
	"Stealth", "Swift", "Quiet", "Bold", "Fierce", "Noble", "Silent", "Brave", "Cosmic", "Wild",
	"Ancient", "Bright", "Calm", "Deep", "Eager", "Frozen", "Golden", "Hidden", "Icy", "Jade",
	"Keen", "Lucky", "Misty", "Neon", "Odd", "Proud", "Royal", "Sharp", "Tough", "Urban",
	"Vivid", "Wise", "Young", "Zesty", "Amber", "Bliss", "Crisp", "Dusk", "Elite", "Frost",
	"Grand", "Hazy", "Iron", "Jolly", "Kind", "Lunar", "Merry", "Nova", "Olive", "Pearl",
	"Quest", "Rapid", "Solar", "Topaz", "Ultra", "Velvet", "Warm", "Azure", "Blaze", "Coral",
	"Dawn", "Ember", "Flint", "Glade", "Heath", "Ivory", "Jewel", "Karma", "Lark", "Moss",
	"Nimbus", "Onyx", "Plush", "Raven", "Sage", "Thorn", "Umber", "Vale", "Wren", "Yarrow",
	"Zephyr", "Alpine", "Birch", "Cedar", "Drift", "Echo", "Fjord", "Glen", "Haven", "Isle",
	"Juniper", "Krill", "Lagoon", "Meadow", "Nacre", "Orbit", "Pine", "Quartz", "Reef", "Storm",
	"Tide", "Urchin", "Veil", "Whisper", "Aura", "Bloom", "Cliff", "Dune", "Ever", "Flare",
	"Grove", "Hollow", "Indigo", "Knot", "Loom", "Mirth", "Nectar", "Oaken", "Plume",
	"Ridge", "Shale", "Thistle", "Under", "Violet", "Wisp", "Zen", "Arcane", "Beryl", "Crypt",
	"Dragon", "Elf", "Fairy", "Giant", "Harpy", "Imp", "Jinn", "Kraken", "Lyre", "Mage",
	"Nymph", "Ogre", "Phoenix", "Quill", "Rune", "Sprite", "Troll", "Unicorn", "Valkyrie", "Wyrm",
	"Yeti", "Abyss", "Brine", "Crest", "Delve", "Ebony", "Fathom", "Glyph", "Horde",
	"Kaleid", "Lumen", "Mirage", "Nebula", "Oracle", "Prism", "Quasar", "Ripple", "Sable", "Tidal",
	"Vertex", "Warp", "Aegis", "Bolt", "Cipher", "Dynamo", "Epoch", "Flux", "Gauss", "Helix",
	"Kernel", "Logic", "Matrix", "Neural", "Octal", "Pixel", "Quantum", "Radar", "Sigma", "Turbo",
	"Union", "Vector", "Watt", "Xenon", "Yield", "Zetta", "Agile", "Brisk", "Chill", "Dapper",
	"Elastic", "Fleet", "Gleam", "Humble", "Jovial", "Lithe", "Mellow", "Nimble", "Pebble", "Rustic",
	"Snug", "Tender", "Upbeat", "Vibrant", "Whimsy", "Ample", "Bouncy", "Cozy", "Dimple", "Fizzy",
	"Giddy", "Hilarious", "Jazzy", "Loopy", "Mimic", "Nutty", "Perky", "Quirky", "Silly", "Tipsy",
	"Wacky", "Zany", "Breezy", "Curly", "Dizzy", "Frumpy", "Goofy", "Huffy", "Jumpy", "Kooky",
	"Lanky", "Moppy", "Nerdy", "Plucky", "Rusty", "Sassy", "Tacky", "Weedy", "Brawny", "Chunky",
	"Drafty", "Fluffy", "Grumpy", "Hefty", "Jumbo", "Lumpy", "Muddy", "Plump", "Scruffy", "Stocky",
	"Sturdy", "Bulky", "Crafty", "Drowsy", "Frugal", "Gloomy", "Hungry", "Jaunty", "Lively", "Moody",
	"Peppy", "Roomy", "Shady", "Sleepy", "Spiffy", "Testy", "Wily", "Woozy", "Beefy", "Bumpy",
	"Canny", "Dingy", "Feisty", "Hasty", "Lacy", "Manky", "Nifty", "Paltry",
	"Randy", "Saucy", "Tawdry", "Vasty", "Yucky", "Balky", "Cagey", "Dicey", "Flimsy",
	"Gauzy", "Hokey", "Jiffy", "Mimsy", "Pithy", "Risky", "Seedy", "Tricky", "Veiny",
	"Wispy", "Crisp", "Dusky", "Frosty", "Glist", "Hazel", "Jasper", "Lilac", "Mauve",
	"Ochre", "Plum", "Russet", "Sienna", "Vermil", "Wheat", "Auburn", "Beryl",
	"Cerise", "Denim", "Fawn", "Ginger", "Indigo", "Khaki", "Lemon", "Maroon", "Navy", "Olive",
	"Peach", "Rust", "Salmon", "Teal", "Blond", "Chest", "Dun", "Fallow", "Honey",
	"Ivory", "Jade", "Lime", "Mint", "Plum", "Rose", "Ruby", "Slate", "Taupe", "Violet",
	"Abrupt", "Blunt", "Chaste", "Dire", "Earnest", "Fond", "Grim", "Hale", "Irate", "Jaded",
	"Keen", "Lax", "Mild", "Naive", "Obtuse", "Pert", "Rash", "Stern", "Terse", "Uptight",
	"Vain", "Wary", "Yawning", "Zealous", "Arid", "Boggy", "Chilly", "Damp", "Frigid", "Gusty",
	"Humid", "Muggy", "Raw", "Soggy", "Tepid", "Windy", "Balmy", "Crisp", "Drizzly",
	"Frosty", "Glacial", "Hazy", "Misty", "Rainy", "Showery", "Steamy", "Temperate", "Breezy", "Cloudy",
	"Dewy", "Foggy", "Gloomy", "Overcast", "Smoggy", "Sunny", "Thundery", "Blustery", "Calm", "Dry",
	"Electric", "Fair", "Grey", "Mild", "Severe", "Stormy", "Warm", "Wet", "Angry", "Crowded",
	"Desolate", "Fertile", "Green", "Lush", "Pristine", "Rocky", "Sandy", "Untamed", "Vast", "Wooded",
	"Barren", "Crystal", "Dark", "Enchanted", "Fallen", "Ghostly", "Haunted", "Lonely", "Misty", "Mystic",
	"Peaceful", "Quiet", "Restless", "Sacred", "Silent", "Tranquil", "Wild", "Ancient", "Blessed", "Cursed",
	"Forbidden", "Hidden", "Lost", "Magical", "Mythic", "Sacred", "Secret", "Silent", "Twilight", "Untold",
	"Arctic", "Boreal", "Coastal", "Desert", "Forest", "Glacial", "Highland", "Island", "Lowland", "Mountain",
	"Oceanic", "Polar", "River", "Sea", "Sky", "Summit", "Tundra", "Valley", "Volcanic", "Wetland",
	"Amber", "Bronze", "Copper", "Gold", "Iron", "Nickel", "Platinum", "Silver", "Steel", "Tin",
	"Titanium", "Zinc", "Brass", "Chrome", "Lead", "Mercury", "Quicksilver", "Alabaster", "Bone", "Coral",
	"Crystal", "Diamond", "Emerald", "Flint", "Granite", "Ivory", "Jade", "Lapis", "Marble", "Onyx",
	"Opal", "Pearl", "Quartz", "Ruby", "Sapphire", "Topaz", "Turquoise", "Agate", "Beryl", "Citrine",
	"Garnet", "Jet", "Malachite", "Obsidian", "Pyrite", "Spinel", "Amethyst", "Azurite", "Bloodstone", "Coal",
}

var animals = []string{
	"Eel", "Fox", "Hawk", "Wolf", "Bear", "Lion", "Deer", "Owl", "Tiger", "Vole",
	"Ant", "Bat", "Cat", "Dog", "Elk", "Fawn", "Gnu", "Hare", "Ibex", "Jay",
	"Koala", "Lynx", "Mole", "Newt", "Oryx", "Pig", "Quail", "Roach", "Seal", "Toad",
	"Urchin", "Viper", "Wren", "Yak", "Zebra", "Anole", "Badger", "Camel", "Dove", "Emu",
	"Finch", "Gecko", "Heron", "Iguana", "Jackal", "Kite", "Lemur", "Manta", "Narwhal", "Okapi",
	"Panther", "Raven", "Salmon", "Turtle", "Whale", "Xerus", "Alpaca", "Beaver", "Coyote",
	"Dingo", "Ermine", "Ferret", "Gopher", "Hyena", "Impala", "Jaguar", "Llama", "Mink",
	"Numbat", "Otter", "Panda", "Quokka", "Raccoon", "Skunk", "Tapir", "Urial", "Vicuna", "Wallaby",
	"Xenops", "Yapok", "Zorilla", "Aardvark", "Buffalo", "Cheetah", "Dolphin", "Elephant", "Flamingo", "Gazelle",
	"Hamster", "Ibis", "Jellyfish", "Kangaroo", "Lobster", "Monkey", "Octopus", "Penguin", "Rhinoceros",
	"Squirrel", "Umbrellabird", "Vulture", "Walrus", "Anglerfish", "Barracuda", "Chameleon", "Dragonfly",
	"Earthworm", "Falcon", "Gorilla", "Hedgehog", "Jackrabbit", "Kingfisher", "Ladybug", "Manatee",
	"Parrot", "Rattlesnake", "Salamander", "Tarantula", "Wolverine", "Axolotl", "Bison", "Caribou",
	"Echidna", "Frog", "Giraffe", "Hippo", "Kookaburra", "Loris", "Moose", "Nutria", "Orangutan",
	"Peacock", "Rhea", "Sloth", "Toucan", "Viperfish", "Wombat", "Zebu", "Ape",
	"Bobcat", "Cobra", "Eagle", "Fossa", "Gavial", "Hornet", "Insect",
	"Lizard", "Marmot", "Nautilus", "Oyster", "Porpoise", "Rabbit", "Scorpion", "Tuna",
	"Wasp", "Yabby", "Zander", "Anaconda", "Boa", "Condor", "Firefly", "Grasshopper",
	"Kestrel", "Leech", "Mantis", "Opossum", "Puffin",
	"Tern", "Vervet", "Weasel", "Addax", "Bongo",
	"Civet", "Dugong", "Eland", "Fennec", "Gaur", "Indri",
	"Kiang", "Langur", "Margay", "Nyala", "Oribi", "Puku", "Quoll", "Ratel", "Sable",
	"Wildebeest", "Agouti", "Capybara", "Gelada",
	"Macaque", "Nilgai", "Pademelon", "Quetzal",
	"Rosella", "Siamang", "Tamarin", "Vanga", "Wagtail",
	"Aardwolf", "Grysbok", "Humpback", "Lechwe", "Muntjac",
	"Pronghorn", "Quelea", "Screamer", "Waterbuck",
	"Albatross", "Bettong", "Cuscus", "Dunnart",
	"Gundi", "Hutia", "Kowari", "Monito", "Nabarlek", "Olingo",
	"Potoroo", "Quokka", "Solenodon", "Tenrec", "Vombat", "Wallaroo",
	"Anchovy", "Blenny", "Clownfish", "Damselfish", "Eel", "Flounder", "Goby", "Haddock",
	"Jackfish", "Killifish", "Lamprey", "Mackerel", "Needlefish", "Opah", "Parrotfish",
	"Sardine", "Tetra", "Vendace", "Wrasse", "Yellowtail", "Zebrafish",
	"Arowana", "Betta", "Catfish", "Dogfish",
	"Grouper", "Halibut", "Koi", "Lungfish", "MahiMahi", "Oscar",
	"Pufferfish", "Rasbora", "Triggerfish", "Whiting", "Yellowfin", "Angelfish",
	"Barracuda", "Cod", "Eel", "Flounder", "Gar", "Herring", "Icefish",
	"Loach", "Minnow", "Perch", "Roach", "Smelt", "Trout", "Wrasse",
	"Anemone", "Barnacle", "Coral", "Limpet", "Mussel",
	"Nudibranch", "Oyster", "Sponge", "Tunicate", "Urchin",
	"Beetle", "Cricket", "Damselfly", "Earwig", "Flea",
	"Grub", "Horsefly", "Ladybug", "Moth", "Silverfish",
	"Termite", "Weevil", "Caterpillar", "Dragonfly", "Firefly",
	"Grasshopper", "Hornet", "Locust", "Mosquito", "Scorpion",
	"Tarantula", "Wasp", "Crab", "Lobster", "Prawn", "Shrimp",
	"Crayfish", "Krill", "Barnacle", "Squid", "Octopus",
	"Jellyfish", "Starfish", "Dolphin", "Porpoise", "Whale",
	"Orca", "Beluga", "Narwhal", "Spermwhale", "Humpback",
	"Bluewhale", "Rightwhale", "Finwhale", "Minkewhale", "Seiwhale",
	"Bryde", "Graywhale", "Pilotwhale", "Killerwhale", "Falsekiller",
	"Melonhead", "Pygmykiller", "Frasers", "Rissos", "Spotted",
	"Spinner", "Bottlenose", "Common", "Striped", "Clymene",
	"Rough", "Hector", "Chilean", "Peruvian", "Commerson",
	"Peale", "Austral", "Hourglass", "Fitzroy", "Dusky",
}

func generateName(counter int64) string {
	adjLen := int64(len(adjectives))
	animLen := int64(len(animals))
	suffixLen := int64(90)

	// Cycle animals fast (each user gets a unique animal)
	animIdx := counter % animLen
	adjIdx := (counter / animLen) % adjLen
	numSuffix := 10 + (counter / (animLen * adjLen)) % suffixLen

	return fmt.Sprintf("%s-%s-%d", adjectives[adjIdx], animals[animIdx], numSuffix)
}
